
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: AzureCLI@1
  displayName: 'Install the CLI'
  inputs:
    azureSubscription: 'azmldemows'
    scriptLocation: inlineScript
    inlineScript: 'az extension add -s https://azuremlsdktestpypi.blob.core.windows.net/wheels/Smoke-tests-windows-az-extension-add/2864553/azure_cli_ml-0.1.0.2864553-py2.py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/Smoke-tests-windows-az-extension-add/2864553 --yes --debug'

- task: AzureCLI@1
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: 'azmldemows'
    scriptLocation: inlineScript
    inlineScript: 'az ml folder attach'
  
- task: AzureCLI@1
  displayName: 'Submit script run'
  inputs:
    azureSubscription: 'azmldemows'
    scriptLocation: inlineScript
    inlineScript: 'az ml run submit-script -c sklearn -e test -d myenv.yml train.py'

- task: AzureCLI@1
  displayName: 'Register model'
  inputs:
    azureSubscription: 'azmldemows'
    scriptLocation: inlineScript
    inlineScript: 'az ml model register -n sklearn_regression_model.pkl -p sklearn_regression_model.pkl'

- task: AzureCLI@1
  displayName: 'Deploy model'
  inputs:
    azureSubscription: 'azmldemows'
    scriptLocation: inlineScript
    inlineScript: 'az ml model deploy -n acicicd -m sklearn_regression_model.pkl:1 --inference-metadata-file inferenceConfig.yml -df deploymentConfig.yml'

- task: AzureCLI@1
  displayName: 'Delete deployed service'
  inputs:
    azureSubscription: 'azmldemows'
    scriptLocation: inlineScript
    inlineScript: 'az ml service delete -n acicicd'

- task: AzureCLI@1
  displayName: 'List pipelines'
  inputs:
    azureSubscription: 'azmldemows'
    scriptLocation: inlineScript
    inlineScript: 'az ml pipeline list'